server:
  port: 9021

spring:
  application:
    name: keyuspan-folder-consumer

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000

eureka:
  client: # 客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
  #       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: keyuspan-folder-consumer
    prefer-ip-address: true     # 访问路径可以显示IP地址

info:
  app.name: keyuspan-folder-consumer
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

# txmanager地址
tm:
  manager:
    url: http://127.0.0.1:8899/tx/manager/

logging:
  level:
    root: debug
    com:
      codingapi: debug

