server:
  port: 9081

spring:
  application:
    name: keyuspan-member-consumer

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: keyuspan-member-consumer
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: keyuspan-member-consumer
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

# txmanager地址
tm:
  manager:
    url: http://127.0.0.1:8070/tx/manager/

logging:
  level:
    root: debug
    com:
      codingapi: debug