server:
  port: 12000

eureka:
  instance:
    instance-id: keyuspan-gateway
    prefer-ip-address: true
  client: # 客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka

spring:
  application:
    name: keyuspan-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true # 启动服务名称全小写的映射方式，自动映射下的访问方式为：http://网关地址/服务名称（小写）/**
          enabled: true # 自动映射
      routes:
        - id: member
          uri: lb://keyuspan-member-consumer  # uri：用lb:// + eureka中注册的微服务名称
          predicates:
            - Method=GET,POST
#            - Path=/**
#          filters:                     #filters：过滤规则
#            - StripPrefix=1

        - id: file
          uri: lb://keyuspan-file-consumer
          predicates:
            - Method=GET,POST
#            - Path=/**
#          filters:
#            - StripPrefix=1

        - id: folder
          uri: lb://keyuspan-folder-consumer
          predicates:
            - Method=GET,POST
#            - Path=/**
#          filters:
#            - StripPrefix=1

        - id: share
          uri: lb://keyuspan-share-consumer
          predicates:
            - Method=GET,POST
#            - Path=/**
#          filters:
#            - StripPrefix=1

info:
  app.name: keyuspan-gateway
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

logging:
  level:
    org.springframework.cloud.gateway: debug