server:
  port: 8061

spring:
  application:
    name: keyuspan-file-provider

  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: keyus
    password: keyus
    url: jdbc:mysql://localhost:3306/keyuspan
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 10                                         # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

  jpa:
    database: mysql
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000

eureka:
  client: # 客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
  #       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: keyuspan-file-provider
    prefer-ip-address: true     # 访问路径可以显示IP地址

# fdfs-client的配置
fdfs:
  so-timeout: 10000
  connect-timeout: 2000
  pool:
    # 从池中借出的对象的最大数目（配置为-1表示不限制）
    max-total: -1
    # 获取连接时的最大等待毫秒数(默认配置为5秒)
    max-wait-millis: 5000
    # 每个key最大连接数
    max-total-per-key: 50
    # 每个key对应的连接池最大空闲连接数
    max-idle-per-key: 10
    # 每个key对应的连接池最小空闲连接数
    min_idle_per_key: 5
  thumb-image:             # 缩略图生成参数
    width: 150
    height: 150
  tracker-list:            # TrackerList参数，支持多个
    - 127.0.0.1:22122
  web-server-url: 127.0.0.1

info:
  app.name: keyuspan-file-provider
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

# txmanager地址
tm:
  manager:
    url: http://127.0.0.1:8899/tx/manager/

logging:
  level:
    sql: debug
    root: debug
    com:
      codingapi: debug
