server:
  port: 9999

spring:
  application:
    name: keyuspan-mail

  mail:
    host: smtp.sina.com
    username: keyus_mail@sina.com
    password: mailmail_keyus
    protocol: smtp #发送邮件协议
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

eureka:
  client: # 客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
  #       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: keyuspan-mail
    prefer-ip-address: true

info:
  app.name: keyuspan-mail
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

logging:
  level:
    root: debug

